@ParametersAreNotNullByDefault
@MethodsReturnNotNullByDefault
package net.thenextlvl.tweaks.command.environment.weather;

import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNotNullByDefault;