@ParametersAreNotNullByDefault
@MethodsReturnNotNullByDefault
package net.thenextlvl.tweaks.command.environment.time;

import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNotNullByDefault;