@ParametersAreNotNullByDefault
@MethodsReturnNotNullByDefault
package net.thenextlvl.tweaks.command.environment.suggestion;

import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNotNullByDefault;