@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.thenextlvl.tweaks.command.environment;

import core.annotation.MethodsReturnNonnullByDefault;
import core.annotation.ParametersAreNonnullByDefault;