name: "TNLTweaks"
version: "1.2"
main: "net.nonswag.tnl.tweaks.Tweaks"
api-version: "1.13"
website: "https://www.thenextlvl.net"
author: "NonSwag"
depend: ["TNLListener"]
commands:
  fly:
  feed:
  heal:
  speed:
  thunder:
  rain:
  sun:
  night:
  day:
  tps:
  ping:
  rights:
  op:
  deop:
  gamemode:
    aliases: ["gm"]
