@ParametersAreNotNullByDefault
@MethodsReturnNotNullByDefault
package net.thenextlvl.tweaks.command.api;

import core.annotation.MethodsReturnNotNullByDefault;
import core.annotation.ParametersAreNotNullByDefault;